### ISSUE TITLE
The minSdkVersion bump to 26 is not needed, it restricts plugin usage

### ISSUE THREAD

**Issue by MrCsabaToth** [tjarvstrand/flutter_timezone#1]
The commit responsible for this https://github.com/tjarvstrand/flutter_timezone/commit/53e8462a23fc8bc5a644ecb33594738cd8c77826 references a page https://developer.android.com/reference/java/time/ZoneId. I see that ZoneId is added in SDK 26, but the usage of it should be optional. 26 min SDK level is too high.

**Comment by MrCsabaToth** [comment]
I think the version bump is a mistake! If you look at the `FlutterTimezonePlugin.kt` then both calls to ZoneId are properly guarded by `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O)`:
* https://github.com/tjarvstrand/flutter_timezone/blob/c46b11cda9d9a444ad47142745e4789da4c9fd30/android/src/main/kotlin/net/wolverinebeach/flutter_timezone/FlutterTimezonePlugin.kt#L48
* https://github.com/tjarvstrand/flutter_timezone/blob/c46b11cda9d9a444ad47142745e4789da4c9fd30/android/src/main/kotlin/net/wolverinebeach/flutter_timezone/FlutterTimezonePlugin.kt#L56

**Comment by MrCsabaToth** [comment]
I understand that some build tools may complain about either deprecated API calls or some other API calls (haven't remember seeing the latter) but it's not uncommon with native feature plugins to branch based on SDK level. I have users with devices with less than SDK level 26, and excluding them unnecessarily is not good (this is why the SD level based branch is there the first place).

**Comment by tjarvstrand** [comment]
Ah, yes. You're totally right. I jumped too fast on that one.

**Comment by tjarvstrand** [comment]
1.0.4 is out now
