### ISSUE TITLE
Android build failure

### ISSUE THREAD

**Issue by MattPitlyk** [tjarvstrand/flutter_timezone#13]
I can build for iOS fine, but am getting the below error when I build for android. I stepped back though the versions and flutter_timezone 1.0.4 builds fine, but this error appears with 1.0.5.

`
1: Task failed with an exception.
-----------
* Where:
Build file 'C:\Users\alien\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_timezone-1.0.5\android\build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':flutter_timezone'.
> No signature of method: build_bm6wi3zj524ovjzl6767mnodv.android() is applicable for argument types: (build_bm6wi3zj524ovjzl6767mnodv$_run_closure2) values: [build_bm6wi3zj524ovjzl6767mnodv$_run_closure2@5ce86bd8]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script 'C:\Users\alien\Documents\flutter\flutter_windows_2.0.1-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 463

* What went wrong:
A problem occurred configuring project ':flutter_timezone'.
> Failed to notify project evaluation listener.
   > Cannot invoke method substring() on null object
   > compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org`

**Comment by tjarvstrand** [comment]
Hello, thanks for taking the time to open an issue :)

Which version of `flutter_timezone` is this? Which version of AGP?

**Comment by tjarvstrand** [comment]
I'll close this for now. Please reopen if you're still seeing issues related to this package.
