### ISSUE TITLE
[Question]: Timezone retrieval safety outside of Flutter

### ISSUE THREAD

**Issue by mrverdant13** [tjarvstrand/flutter_timezone#14]
Hey there! 👋🏼 

I would like to know if it is possible to get the device locale when invoked in an independent isolate or context e.g bg notification handler ?

Thanks! ✌🏼

**Comment by tjarvstrand** [comment]
Hi, sorry for the late response. As long as you take the necessary steps to set up everything needed for the Flutter method channel to work, I see no reason it shouldn't work.

**Comment by tjarvstrand** [comment]
I'm not sure what else I can do here so I'll close this for now.  Please reopen if you experience any problems.
