### ISSUE TITLE
Missing Plugin Exception 

### ISSUE THREAD

**Issue by pranavo72bex** [tjarvstrand/flutter_timezone#17]
I am getting this error message frequently 
`flutter_timezone: ^1.0.6`
`Flutter version 3.7.12 `

![Screenshot 2023-08-22 at 11 38 39](https://github.com/tjarvstrand/flutter_timezone/assets/71395812/8f5d85f5-f636-4952-8529-66c1a11e5646)

**Comment by tjarvstrand** [comment]
Hey @pranavo72bex 

This looks like a problem with your build environment rather than something in `flutter_timezone`. Does this occur when you build from scratch? I.e., after a `flutter clean` (and `cd ios; pod deintegrate` if on iOS)?

**Comment by pranavo72bex** [comment]
Thanks.. problem solved after flutter clean
