### ISSUE TITLE
time zone has been deemed obsolete.

### ISSUE THREAD

**Issue by vipthuocno** [tjarvstrand/flutter_timezone#19]
I got the timezone "Asia/SaiGon" on my iphone.
The Asia/Saigon time zone has been deemed obsolete. It has been replaced by Asia/Ho_Chi_Minh.
Need latest update.
Thanks

**Comment by tjarvstrand** [comment]
Thanks for taking the time to report an issue. 

However, flutter_timezone does actually provide any time zone days itself. It only provides access to the data provided by the underlying platform. If that is obsolete, you'll have to see if you can update your device to get the correct time zones.
