### ISSUE TITLE
flutter_timezone\FlutterTimezonePlugin.kt  as it does not exist

### ISSUE THREAD

**Issue by yunxingyu** [tjarvstrand/flutter_timezone#28]
Execution failed for task ':flutter_timezone:compileDebugKotlin'.
> Cannot fingerprint input file property 'sources': Failed to create MD5 hash for file 'C:\Users\andapro.Xie\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\flutter_timezone-1.0.8\android\src\main\kotlin\net\wolverinebeach\flutter_timezone\FlutterTimezonePlugin.kt' as it does not exist.

**Comment by tjarvstrand** [comment]
This looks like an environment issue to me. The file is definitely there.

**Comment by tjarvstrand** [comment]
I'll close this for now. Feel free to reopen if you think there really is an issue with flutter_timezone.
