### ISSUE TITLE
Uncaught MissingPluginException(No implementation found for method getLocalTimezone on channel flutter_timezone)

### ISSUE THREAD

**Issue by duchv-selex** [tjarvstrand/flutter_timezone#32]
I build my web with parameter `--web-renderer canvaskit --release --dart-define=Dart2jsOptimization=O0` 

But i have an error  same https://github.com/tjarvstrand/flutter_timezone/issues/26

How to fix that here.

Uncaught MissingPluginException(No implementation found for method getLocalTimezone on channel flutter_timezone)
    at Object.d (http://aubin.localhost/main.dart.js:5407:19)
    at http://aubin.localhost/main.dart.js:103915:15
    at blw.a (http://aubin.localhost/main.dart.js:6787:63)
    at blw.$2 (http://aubin.localhost/main.dart.js:56568:14)
    at bka.$1 (http://aubin.localhost/main.dart.js:56562:21)
    at XP.F9 (http://aubin.localhost/main.dart.js:57753:33)
    at bas.$0 (http://aubin.localhost/main.dart.js:57036:11)
    at Object.Js (http://aubin.localhost/main.dart.js:6950:40)
    at ag.pt (http://aubin.localhost/main.dart.js:56961:3)
    at bal.$0 (http://aubin.localhost/main.dart.js:57006:13)

**Comment by duchv-selex** [comment]
release in chrome Version 126.0.6478.127 (Official Build) (arm64)

**Comment by tjarvstrand** [comment]
Did you try running `flutter clean` and rebuilding your project?

**Comment by duchv-selex** [comment]
@tjarvstrand Sometimes I run flutter clean before building

**Comment by tjarvstrand** [comment]
Hi @duchv-selex,

It seems to me like this is somehow related to your local build since the error seems to indicate that the plugin code is missing.

**Comment by tjarvstrand** [comment]
Have you been able to solve your  issue? 

Sadly, I'm not sure how I can be of more assistance without a reliable way to reproduce the issue.

**Comment by duchv-selex** [comment]
@tjarvstrand I'm currently dealing with other issues so I haven't gone back to investigate this error yet. I will report further if more information becomes available

**Comment by cmaccarone** [comment]
im also seeing this

**Comment by fbardecio** [comment]
I was facing the same issue, but it got fixed after running `flutter clean`, `flutter pub get` and re building the app.

**Comment by berkanaslan** [comment]
I was facing the same issue on Chrome arm64, and @fbardecio as said it got fixed after running `flutter clean`, `flutter pub get `. I think the issue can be closed.

**Comment by tjarvstrand** [comment]
Closing for now. Feel free to reopen if you still think there's an issue with `flutter_timezone`

**Comment by quangmueaoeiga** [comment]
> 我遇到了同样的问题，但运行并重新构建应用程序后问题就得到了`flutter clean`解决`flutter pub get`。

YES, Re-run the App. flutter clean & flutter pub get
