### ISSUE TITLE
> Could not resolve all files for configuration ':flutter_timezone:classpath'.    > Could not download kotlin-compiler-embeddable-1.6.10.jar

### ISSUE THREAD

**Issue by lucasjinreal** [tjarvstrand/flutter_timezone#7]
> Could not resolve all files for configuration ':flutter_timezone:classpath'.
   > Could not download kotlin-compiler-embeddable-1.6.10.jar

**Comment by tjarvstrand** [comment]
Hi!

This looks unrelated to flutter_timezone. Possibly a network error? 

In any case, the message is complaining about `kotlin-compiler-embeddable`, not flutter_timezone.

**Comment by tjarvstrand** [comment]
It's been a while so I'm going to close this now. Feel free to re-open if you still have problems.
